apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedding
  template:
    metadata:
      labels:
        app: embedding
    spec:
      containers:
      - name: embedding
        image: $CI_REGISTRY_IMAGE/embedding:$CI_COMMIT_SHORT_SHA
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: embedding-service
spec:
  selector:
    app: embedding
  ports:
  - port: 80
    targetPort: 80
