apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag
  template:
    metadata:
      labels:
        app: rag
    spec:
      containers:
      - name: rag
        image: $CI_REGISTRY_IMAGE/rag:$CI_COMMIT_SHORT_SHA
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rag-service
spec:
  selector:
    app: rag
  ports:
  - port: 80
    targetPort: 80
