apiVersion: apps/v1
kind: Deployment
metadata:
  name: vectordb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vectordb
  template:
    metadata:
      labels:
        app: vectordb
    spec:
      containers:
      - name: vectordb
        image: $CI_REGISTRY_IMAGE/vectordb:$CI_COMMIT_SHORT_SHA
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vectordb-service
spec:
  selector:
    app: vectordb
  ports:
  - port: 80
    targetPort: 80
